#! /usr/bin/python

# Git pre-commit hook
#
# Installation instructions:
# Symbolically link this file to .git/hooks with `cd .git/hooks; ln -s ../../pre-commit pre-commit'

import os, sys, unittest
if os.getcwd().split('/')[-1] == 'hooks':
	os.chdir('../..')
sys.path.append(os.getcwd())
from epicparser import *


class TestTrowel(unittest.TestCase):


	# Parse tests
	def test_parse_print_number(self):
		self.assertEqual(parsewrapper().gettokens("print 45"), [['UNKNOWNWORD', 'print', 1], ['NUMVAL', '45', 1]])
		self.assertEqual(parsewrapper().gettokens("print 4 5"), [['UNKNOWNWORD', 'print', 1], ['NUMVAL', '4', 1], ['NUMVAL', '5', 1]])

	# Sample program tests

if __name__ == '__main__':
	unittest.main()