#!/usr/bin/python
import sys, os, subprocess
directory = os.listdir('.')
for filename in directory:
	if filename[-3:] == 'pyc':
		print '- ' + filename
		os.remove(filename)

from stat import *

filename = sys.argv[1]

subprocess.call(['./epicparser.py', filename])
target_filename = filename.split('.')[0] + '.py'
os.chmod(target_filename, S_IRUSR+S_IWUSR+S_IXUSR) # give owner execute permissions
subprocess.call(target_filename)
